## Load the Data

```{r}

library(tidyverse)
library(ggplot2)

d_full <- bind_rows(
  read_csv("/Users/kamalpathak/Desktop/POLI3148_DaSPPA_Portfolio/_DataPublic_/vdem/1789_1827/vdem_1789_1827_external.csv")
, 
 read_csv("/Users/kamalpathak/Desktop/POLI3148_DaSPPA_Portfolio/_DataPublic_/vdem/1867_1905/vdem_1867_1905_external.csv")
,
 read_csv("/Users/kamalpathak/Desktop/POLI3148_DaSPPA_Portfolio/_DataPublic_/vdem/1906_1944/vdem_1906_1944_external.csv")
,
 read_csv("/Users/kamalpathak/Desktop/POLI3148_DaSPPA_Portfolio/_DataPublic_/vdem/1945_1983/vdem_1945_1983_external.csv")
,
  read_csv("/Users/kamalpathak/Desktop/POLI3148_DaSPPA_Portfolio/_DataPublic_/vdem/1984_2022/vdem_1984_2022_external.csv")
) 
  




```

## Select Indicators of Interest 

```{r}


d <- d_full |>
  select(
    country_text_id, year, 
    e_regiongeo, e_pelifeex, e_gdppc, 
    e_mipopula, e_wb_pop, e_peinfmor,
    e_boix_regime, e_lexical_index, e_p_polity) |>
  rename("region" = "e_regiongeo", 
         "life_expectancy" = "e_pelifeex", 
         "gdppc" = "e_gdppc",
         "population_ClioInfra" = "e_mipopula", 
         "population_WorldBank" = "e_wb_pop",
         "infant_mortality" = "e_peinfmor",
         "democracy_binary" = "e_boix_regime",
         "democracy_lexical" = "e_lexical_index",
         "democracy_polity5" = "e_p_polity") |>
  filter(year >= 1800)



glimpse(d)
```

## Multiple Population Data Sources

```{r}


# Check years that are available in both datasets.

d_pop_overlap <- d |> select(country_text_id, year, starts_with("population_")) |> 
  drop_na()
print(d_pop_overlap, n = 3)


unique(d_pop_overlap$year)
```

```{r}


# STEP 1: "Harmonize" the units
d <- d |> mutate(population_WorldBank = population_WorldBank / 1000)

# STEP 2 Method 1: Slower but use only tidyverse functionality
# [Slow! Not recommended!]
d <- d |> rowwise() |>
  mutate(population = mean(c_across(c("population_ClioInfra", "population_WorldBank")), 
                           na.rm = TRUE), .after = population_WorldBank) |>
  ungroup()

# STEP 2 Method 2: Faster but use a non-tidyverse function rowMeans() 
# and create a temporary vector tmp_population, which I remove after use with rm()
# [Faster !Recommended!]
tmp_population <- d |> select(population_ClioInfra, population_WorldBank) |> rowMeans(na.rm = TRUE)
d <- d |> mutate(population = !!(tmp_population), .after = population_WorldBank)

rm(tmp_population)

# Remove the columns we no longer need
d <- d |> select(-population_ClioInfra, -population_WorldBank)


summary(d)
```

## Sanity Check

```{r}

summary(d %>% select(-country_text_id, -year, -region))

```

## Check Data Availability

```{r}

check_data_available <- d |> 
  mutate(Available = (!is.na(life_expectancy) & !is.na(gdppc) & !is.na(population))) 

table(check_data_available$Available, useNA = "always")


check_data_available |> print(n = 3)

```

```{r}

check_data_available_wide <- check_data_available |>
  select(country_text_id, year, Available) |>
  pivot_wider(names_from = "country_text_id", values_from = "Available", 
              names_prefix = "c_") |>
  arrange(year)

check_data_available_wide |> print(n = 3)
```

```{r}

# Check, for each year, the availability of each column
check_data_available_by_column <- d |>
  group_by(year) |>
  summarise(
    life_expectancy = sum(is.na(life_expectancy)),
    gdppc = sum(is.na(gdppc)),
    population = sum(is.na(population))
  )


  # above is an alternative way to write the summarise() step

check_data_available_by_column |> print(n = 3)
```

# Data Viz Basics

## Simple Scatter Plot

```{r}

d <- d |> 
  ggplot(aes(x = gdppc, y = life_expectancy)) + 
  geom_point() +
  labs(x = "GDP per capita", y = "Life Expectancy", 
       title = "Wealth and Health in the World (1800-2019)",
       caption = "By Kamal")



```

## Set Themes : theme_bw

```{r}

d + theme_bw()
```

## The Economist Theme

```{r}

library(ggthemes)
d + theme_economist()



```

## Wall Street Journal Theme 

```{r}

d + theme_wsj(base_size = 6)

```
